### ISSUE TITLE
Error: Cannot find module 'table-fit-columns-width'

### ISSUE THREAD

**Issue by codinggirl** [codinggirl/table-fit-columns-width#2]
When package files using browserify, run:

```
npx browserify --debug --entry src/vis/main.js --outfile assets/dist/vis.js
```

The error occurs:

```
Error: Cannot find module 'table-fit-columns-width' from '/Users/meng/workspace/ec/sj/sj-app-tree/src/vis'
    at /Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/meng/workspace/ec/sj/sj-app-tree/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by codinggirl** [comment]
Closed via #1.
